version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_PASSWORD = "mnchuCukImbN5vgU"
      - MONGO_USERNAME = "jesicabodas13"
      - MONGO_DB = Agency_db
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  redis_data:
  mongo_data:

networks:
  app_network:
    driver: bridge
